/* EscapeVerse — motore immersivo per tutte le stanze */
(() => {
  const game = { selectedItem:null, hour:12, minute:0 };
  const hasItem=name=>state&&state.inventory.some(x=>x.name===name);
  const selectedIs=name=>game.selectedItem===name&&hasItem(name);
  const addNote=text=>{if(state&&!state.notes.includes(text))state.notes.push(text)};
  const roomLabel=()=>selected.id==='archivio47'?'Sala documenti':selected.names?.[0]||selected.title;

  function addItem(name,icon){if(!hasItem(name))state.inventory.push({name,icon});renderInteractiveInventory()}
  function renderInteractiveInventory(){
    const box=document.querySelector('#inventoryItems');
    if(!state||!state.inventory.length){box.innerHTML='<span class="empty">Vuoto</span>';return}
    box.innerHTML=state.inventory.map(i=>`<button class="inventory-item interactive ${game.selectedItem===i.name?'selected':''}" data-item="${i.name}"><span>${i.icon}</span>${i.name}</button>`).join('');
    box.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{game.selectedItem=game.selectedItem===b.dataset.item?null:b.dataset.item;renderInteractiveInventory();status(game.selectedItem?`${game.selectedItem} selezionato: tocca dove vuoi usarlo`:'Oggetto deselezionato')})
  }
  function status(text){const s=document.querySelector('.room-status');if(!s)return;s.textContent=text;clearTimeout(status.t);status.t=setTimeout(()=>s.textContent='Tocca gli oggetti per esaminarli',2600)}
  function palette(){const [a,b,c]=selected.colors;return `--room-top:${a};--room-bottom:${b};--room-accent:${c};--room-side:${b};--room-center:${a};--floor-a:${b};--floor-b:${a}`}
  function renderScene(){
    document.querySelector('#sceneBackdrop').style.background='transparent';
    const solved=state.flags||{};
    document.querySelector('#sceneObjects').innerHTML=`<div class="immersive-scene" data-theme="${selected.theme}" style="${palette()}"><div class="immersive-room"></div><div class="immersive-floor"></div>${selected.objects.map((o,i)=>`<button class="room-hotspot ${solved['p'+i]?'solved':''}" data-target="${i}" aria-label="${selected.names[i]}"><span class="room-object">${o}</span><small>${selected.names[i]}</small></button>`).join('')}<div class="room-status">Tocca gli oggetti per esaminarli</div><div class="immersive-flicker"></div></div>`;
    document.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>inspect(Number(b.dataset.target)))
  }
  function startImmersive(){
    clearInterval(timerId);state={time:selected.minutes*60,hints:selected.difficulty==='nightmare'?1:3,hintsUsed:0,step:0,inventory:[],notes:[],escaped:false,flags:{}};game.selectedItem=null;game.hour=12;game.minute=0;
    document.querySelector('#gameCase').textContent=selected.id==='archivio47'?'ARCHIVIO 47':selected.case;document.querySelector('#gameTitle').textContent=roomLabel();document.querySelector('#hintCount').textContent=state.hints;renderScene();renderInteractiveInventory();updateTimer();show('game');
    timerId=setInterval(()=>{if(state.time>0&&!state.escaped){state.time--;updateTimer()}else if(!state.escaped){clearInterval(timerId);modal(`<h2>Tempo scaduto</h2><p>${selected.title} si richiude.</p><button id="retryImmersive" class="action-btn">Riprova</button>`);setTimeout(()=>document.querySelector('#retryImmersive').onclick=()=>{closeModal();startImmersive()},0)}},1000)
  }
  function inspect(i){if(selected.id==='archivio47')return inspectArchive(i);return [genericClue,genericFirstLock,genericSecondLock,genericTool,genericDoor][i]()}

  function genericClue(){if(state.flags.p0)return modal(`<h2>${selected.names[0]}</h2><div class="object-art">${selected.objects[0]}</div><p>Hai già raccolto l’indizio.</p>`);modal(`<h2>${selected.names[0]}</h2><div class="object-art">${selected.objects[0]}</div><p>Osservando con attenzione trovi un dettaglio nascosto.</p><div class="clue">${selected.clue}</div><button id="collectClue" class="puzzle-action" style="width:100%;margin-top:12px">RACCOGLI INDIZIO</button>`);setTimeout(()=>document.querySelector('#collectClue').onclick=()=>{state.flags.p0=true;state.step=1;addItem(selected.items[0][0],selected.items[0][1]);addNote(selected.clue);renderScene();closeModal()},0)}
  function codePuzzle(title,icon,text,code,onSuccess,max=4){modal(`<h2>${title}</h2><div class="object-art">${icon}</div><p>${text}</p><div class="code-input"><input id="immersiveCode" inputmode="numeric" maxlength="${max}" placeholder="${'0'.repeat(max)}"><button id="tryImmersiveCode">PROVA</button></div><div id="immersiveMsg"></div>`);setTimeout(()=>document.querySelector('#tryImmersiveCode').onclick=()=>{if(document.querySelector('#immersiveCode').value===code){onSuccess();document.querySelector('#immersiveMsg').innerHTML='<p class="success">Il meccanismo si sblocca.</p>'}else document.querySelector('#immersiveMsg').innerHTML='<p class="error">Codice errato.</p>'},0)}
  function genericFirstLock(){if(!state.flags.p0)return modal(`<h2>${selected.names[1]}</h2><div class="object-art">${selected.objects[1]}</div><p>Non hai ancora abbastanza informazioni.</p>`);if(state.flags.p1)return modal(`<h2>${selected.names[1]}</h2><p>Il vano è già aperto.</p>`);codePuzzle(selected.names[1],selected.objects[1],'Usa l’orario indicato nell’indizio, senza i due punti.',selected.codes[0],()=>{state.flags.p1=true;state.step=2;addItem(selected.items[1][0],selected.items[1][1]);renderScene()})}
  function genericSecondLock(){const tool=selected.items[1][0];if(!state.flags.p1)return modal(`<h2>${selected.names[2]}</h2><div class="object-art">${selected.objects[2]}</div><p>È bloccato. Devi prima aprire il secondo elemento.</p>`);if(state.flags.p2)return modal(`<h2>${selected.names[2]}</h2><p>Non è rimasto altro.</p>`);if(!selectedIs(tool))return modal(`<h2>${selected.names[2]}</h2><p class="tool-warning">Seleziona “${tool}” nell’inventario e tocca nuovamente questo oggetto.</p>`);codePuzzle(selected.names[2],selected.objects[2],'Inserisci il numero principale citato nell’indizio.',selected.codes[1],()=>{state.flags.p2=true;state.step=3;game.selectedItem=null;addItem(selected.items[2][0],selected.items[2][1]);renderScene()},2)}
  function genericTool(){const tool=selected.items[2][0];if(!state.flags.p2)return modal(`<h2>${selected.names[3]}</h2><div class="object-art">${selected.objects[3]}</div><p>Non riesci ad aprirlo a mani nude.</p>`);if(state.flags.p3)return modal(`<h2>${selected.names[3]}</h2><p>Hai già recuperato ciò che conteneva.</p>`);if(!selectedIs(tool))return modal(`<h2>${selected.names[3]}</h2><p class="tool-warning">Seleziona “${tool}” nell’inventario e usalo qui.</p>`);state.flags.p3=true;state.step=4;game.selectedItem=null;addItem(selected.items[3][0],selected.items[3][1]);addNote(`Hai recuperato ${selected.items[3][0]}.`);renderScene();modal(`<h2>${selected.names[3]}</h2><div class="object-art">${selected.items[3][1]}</div><p class="tool-success">Recuperi ${selected.items[3][0]}.</p>`)}
  function genericDoor(){const pass=selected.items[3][0];if(!state.flags.p3)return modal(`<h2>${selected.names[4]}</h2><div class="object-art">${selected.objects[4]}</div><p>Il sistema finale non è ancora pronto.</p>`);if(!selectedIs(pass))return modal(`<h2>${selected.names[4]}</h2><p class="tool-warning">Seleziona “${pass}” nell’inventario e usalo sull’uscita.</p>`);codePuzzle(selected.names[4],selected.objects[4],'Combina il numero principale con le ultime due cifre dell’orario.',selected.codes[2],()=>{game.selectedItem=null;finish()})}

  function inspectArchive(i){return [archiveShelf,archiveClock,archiveDesk,archiveVent,archiveDoor][i]()}
  function archiveShelf(){if(state.flags.p0)return modal('<h2>Scaffale 7</h2><p>Hai già recuperato tutto dal fascicolo 47.</p>');modal('<h2>Scaffale 7</h2><div class="object-art">📚</div><p>Quale fascicolo controlli?</p><div class="puzzle-grid"><button class="puzzle-choice" data-file="12">12</button><button class="puzzle-choice" data-file="47">47</button><button class="puzzle-choice" data-file="83">83</button></div><div id="fileResult"></div>');setTimeout(()=>document.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>{const r=document.querySelector('#fileResult');if(b.dataset.file!=='47'){r.innerHTML='<p class="error">Solo documenti inutili.</p>';return}b.classList.add('correct');r.innerHTML='<p class="success">Trovi quattro pezzi di una fotografia.</p><button id="buildPhoto" class="puzzle-action">RICOMPONI FOTO</button>';document.querySelector('#buildPhoto').onclick=archivePhoto}),0)}
  function archivePhoto(){modal('<h2>Fotografia strappata</h2><p>Tocca i pezzi nell’ordine corretto.</p><div class="photo-pieces"><button class="photo-piece" data-piece="1">🕙</button><button class="photo-piece" data-piece="3">4</button><button class="photo-piece" data-piece="2">:</button><button class="photo-piece" data-piece="4">7</button></div><p id="photoMsg">Pezzi sistemati: 0/4</p>');let expected=1;setTimeout(()=>document.querySelectorAll('[data-piece]').forEach(p=>p.onclick=()=>{const n=Number(p.dataset.piece);if(n!==expected){expected=1;document.querySelectorAll('[data-piece]').forEach(x=>x.classList.remove('placed'));document.querySelector('#photoMsg').textContent='Ordine errato. Riprova.';return}p.classList.add('placed');expected++;document.querySelector('#photoMsg').textContent=`Pezzi sistemati: ${expected-1}/4`;if(expected===5){state.flags.p0=true;state.step=1;addItem('Foto ricomposta','📷');addNote('La fotografia mostra un orologio fermo alle 10:10 e il numero 47.');renderScene();setTimeout(()=>modal('<h2>Fotografia ricomposta</h2><div class="clue">L’orologio segna 10:10. Sul retro: FASCICOLO 47.</div>'),250)}}),0)}
  function updateClock(){document.querySelector('.clock-hand.hour').style.transform=`rotate(${(game.hour%12)*30+game.minute*.5}deg)`;document.querySelector('.clock-hand.minute').style.transform=`rotate(${game.minute*6}deg)`;document.querySelector('#clockReadout').textContent=`${String(game.hour).padStart(2,'0')}:${String(game.minute).padStart(2,'0')}`}
  function archiveClock(){if(!state.flags.p0)return modal('<h2>Orologio fermo</h2><p>Non sai ancora quale ora impostare.</p>');if(state.flags.p1)return modal('<h2>Orologio</h2><p>Lo scomparto è già aperto.</p>');modal('<h2>Orologio fermo</h2><p>Regola manualmente le lancette.</p><div class="clock-puzzle"><div class="clock-face"><div class="clock-hand hour"></div><div class="clock-hand minute"></div><div class="clock-center"></div></div><strong id="clockReadout">12:00</strong><div class="clock-controls"><button id="hourBtn">+ 1 ORA</button><button id="minuteBtn">+ 5 MIN</button></div><button id="confirmClock" class="puzzle-action" style="width:100%;margin-top:10px">CONFERMA ORA</button><p id="clockMsg"></p></div>');setTimeout(()=>{updateClock();document.querySelector('#hourBtn').onclick=()=>{game.hour=game.hour%12+1;updateClock()};document.querySelector('#minuteBtn').onclick=()=>{game.minute=(game.minute+5)%60;updateClock()};document.querySelector('#confirmClock').onclick=()=>{if(game.hour===10&&game.minute===10){state.flags.p1=true;state.step=2;addItem('Chiave piccola','🗝️');renderScene();document.querySelector('#clockMsg').innerHTML='<span class="success">Compare una chiave.</span>'}else document.querySelector('#clockMsg').innerHTML='<span class="error">Non accade nulla.</span>'}},0)}
  function archiveDesk(){if(state.flags.p2)return modal('<h2>Scrivania</h2><p>Il cassetto è vuoto.</p>');if(!selectedIs('Chiave piccola'))return modal('<h2>Scrivania chiusa</h2><p class="tool-warning">Seleziona la Chiave piccola nell’inventario e usala qui.</p>');state.flags.p2=true;state.step=3;game.selectedItem=null;addItem('Cacciavite','🪛');renderScene();modal('<h2>Cassetto aperto</h2><div class="object-art">🪛</div><p class="tool-success">Trovi un cacciavite.</p>')}
  function archiveVent(){if(state.flags.p3)return modal('<h2>Grata rimossa</h2><p>Il vano è vuoto.</p>');if(!selectedIs('Cacciavite'))return modal('<h2>Grata avvitata</h2><p class="tool-warning">Seleziona il Cacciavite nell’inventario e usalo qui.</p>');state.flags.p3=true;state.step=4;game.selectedItem=null;addItem('Tessera 47','💳');addNote('Sul retro della tessera: “Il fascicolo precede il tempo”.');renderScene();modal('<h2>Vano segreto</h2><div class="object-art">💳</div><p class="tool-success">Trovi la Tessera 47.</p>')}
  function archiveDoor(){if(!state.flags.p3)return modal('<h2>Porta blindata</h2><p>Il lettore richiede una tessera.</p>');if(!selectedIs('Tessera 47'))return modal('<h2>Porta blindata</h2><p class="tool-warning">Seleziona la Tessera 47 e avvicinala al lettore.</p>');codePuzzle('Accesso finale','🚪','Il fascicolo precede il tempo.','4710',()=>{game.selectedItem=null;finish()})}

  function immersiveHint(){if(!state||state.hints<=0)return modal('<h2>Nessun indizio rimasto</h2><p>Rileggi gli appunti e prova a usare gli oggetti raccolti.</p>');const archiveHints=['Cerca il fascicolo 47.','La fotografia mostra l’ora corretta.','Seleziona la chiave prima della scrivania.','Usa il cacciavite sulla grata.','Seleziona la tessera e combina 47 con 10.'];const genericHints=['Esamina il primo oggetto per trovare l’indizio.','Usa l’orario dell’indizio sul secondo oggetto.','Seleziona l’oggetto appena ottenuto prima di toccare il terzo.','Usa lo strumento sul quarto oggetto.','Seleziona l’ultimo oggetto e usa il codice combinato sull’uscita.'];state.hints--;state.hintsUsed++;document.querySelector('#hintCount').textContent=state.hints;const list=selected.id==='archivio47'?archiveHints:genericHints;modal(`<h2>Indizio</h2><p>${list[Math.min(state.step,list.length-1)]}</p>`)}

  document.querySelector('#playBtn').onclick=startImmersive;
  document.querySelector('#hintBtn').onclick=immersiveHint;
  document.querySelector('#notesBtn').onclick=()=>modal(`<h2>Appunti</h2><p>${state&&state.notes.length?state.notes.map(x=>'• '+x).join('<br><br>'):'Non hai ancora trovato indizi.'}</p>`);
})();