/* Nave Eos — Caso 08, motore dedicato con 8 enigmi reali */
(()=>{
const q=s=>document.querySelector(s),eos={selected:null,seq:[]};
const active=()=>typeof selected!=='undefined'&&selected?.id==='astronave';
const has=n=>state?.inventory?.some(i=>i.name===n),chosen=n=>eos.selected===n&&has(n);
const remember=t=>{if(state&&!state.notes.includes(t))state.notes.push(t)};
function inventory(){const b=q('#inventoryItems');if(!b||!state)return;b.innerHTML=state.inventory.length?state.inventory.map(i=>`<button class="inventory-item eos-item ${eos.selected===i.name?'selected':''}" data-eos-item="${i.name}"><span>${i.icon}</span>${i.name}</button>`).join(''):'<span class="empty">Vuoto</span>';b.querySelectorAll('[data-eos-item]').forEach(x=>x.onclick=()=>{eos.selected=eos.selected===x.dataset.eosItem?null:x.dataset.eosItem;inventory()})}
function add(n,i){if(!has(n))state.inventory.push({name:n,icon:i});inventory()}function remove(n){state.inventory=state.inventory.filter(i=>i.name!==n);if(eos.selected===n)eos.selected=null;inventory()}
const hot=(id,done)=>`<button class="eos-hot h-${id} ${done?'done':''}" data-eos="${id}" aria-label="${id}"></button>`;
function render(){const f=state.flags;document.body.classList.add('eos-active');q('#sceneBackdrop').style.background='transparent';q('#sceneObjects').innerHTML=`<div class="eos"><div class="eos-stars"></div><div class="eos-window"></div><div class="eos-floor"></div><div class="eos-reactor"></div><div class="eos-console"></div><div class="eos-nav"></div><div class="eos-cryo"></div><div class="eos-cargo"></div><div class="eos-hatch"></div>${hot('reactor',f.reactor)}${hot('log',f.log)}${hot('nav',f.nav)}${hot('cryo',f.cryo)}${hot('systems',f.systems)}${hot('cargo',f.cargo)}${hot('launch',f.launch)}${hot('hatch',f.hatch)}<div class="eos-status">Ripristina i sistemi della nave e prepara il modulo di fuga</div></div>`;q('.look-hint')?.style.setProperty('display','none','important');q('#sceneObjects').querySelectorAll('[data-eos]').forEach(b=>b.onclick=()=>inspect(b.dataset.eos))}
function start(){if(!active())return;clearInterval(timerId);state={time:32*60,hints:3,hintsUsed:0,step:0,inventory:[],notes:[],escaped:false,flags:{}};eos.selected=null;eos.seq=[];q('#gameCase').textContent='CASO 08';q('#gameTitle').textContent='Nave Eos';q('#hintCount').textContent='3';render();inventory();updateTimer();show('game');modal('<h2>Nave Eos</h2><p>La nave è fuori rotta, la gravità è instabile e il reattore sta cedendo. Riattiva gli otto sistemi prima del collasso.</p><button id="eosIntro" class="action-btn">PRENDI IL COMANDO</button>');setTimeout(()=>{const b=q('#eosIntro');if(b)b.onclick=closeModal},0);timerId=setInterval(()=>{if(state.time>0&&!state.escaped){state.time--;updateTimer()}else if(!state.escaped){clearInterval(timerId);modal('<h2>Reattore collassato</h2><p>La Nave Eos scompare nel bagliore della stella.</p>')}},1000)}
function inspect(id){({reactor,log,nav,cryo,systems,cargo,launch,hatch}[id]||(()=>{}))()}
function reactor(){if(state.flags.reactor)return modal('<h2>Reattore</h2><p>Energia stabilizzata: 3–1–4.</p>');eos.seq=[];modal('<h2>1. Ripristino alimentazione</h2><p>Attiva i circuiti in ordine crescente di temperatura: 3, 1, 4.</p><div class="eos-grid">${[1,2,3,4].map(n=>`<button data-er="${n}">${n}</button>`).join('')}</div><p id="eosMsg"></p>');setTimeout(()=>q('#modalContent').querySelectorAll('[data-er]').forEach(b=>b.onclick=()=>{eos.seq.push(b.dataset.er);if(eos.seq.length===3){if(eos.seq.join('')==='314'){state.flags.reactor=true;state.step=1;add('Chiave dati','💠');remember('Reattore stabilizzato con 3–1–4.');render();q('#eosMsg').innerHTML='<span class="success">ENERGIA RIPRISTINATA</span>'}else{eos.seq=[];q('#eosMsg').innerHTML='<span class="error">Sequenza errata.</span>'}}}),0)}
function log(){if(!state.flags.reactor)return modal('<h2>Terminale capitano</h2><p>Il terminale è senza alimentazione.</p>');if(state.flags.log)return modal('<h2>Terminale capitano</h2><p>Risveglio 02:49 · Equipaggio 73.</p>');if(!chosen('Chiave dati'))return modal('<h2>Terminale capitano</h2><p>Seleziona la Chiave dati nell’inventario.</p>');remove('Chiave dati');state.flags.log=true;state.step=2;add('Log del capitano','💾');remember('Risveglio 02:49. Equipaggio 73. Rotta: △ ○ □.');render();modal('<h2>2. Codice del capitano</h2><div class="clue">RISVEGLIO 02:49<br>EQUIPAGGIO 73<br>ROTTA △ → ○ → □</div>')}
function nav(){if(!state.flags.log)return modal('<h2>Mappa stellare</h2><p>Serve prima il log del capitano.</p>');if(state.flags.nav)return modal('<h2>Mappa stellare</h2><p>Rotta caricata: △ ○ □.</p>');eos.seq=[];modal('<h2>3. Modulo di navigazione</h2><p>Riproduci la rotta registrata.</p><div class="eos-grid"><button data-en="T">△</button><button data-en="C">○</button><button data-en="Q">□</button><button data-en="X">✕</button></div><p id="eosMsg"></p>');setTimeout(()=>q('#modalContent').querySelectorAll('[data-en]').forEach(b=>b.onclick=()=>{eos.seq.push(b.dataset.en);if(eos.seq.length===3){if(eos.seq.join('')==='TCQ'){state.flags.nav=true;state.step=3;add('Gancio magnetico','🧲');remember('Rotta stellare △ ○ □ caricata.');render();q('#eosMsg').innerHTML='<span class="success">ROTTA CONFERMATA</span>'}else{eos.seq=[];q('#eosMsg').innerHTML='<span class="error">Rotta errata.</span>'}}}),0)}
function cryo(){if(!state.flags.nav)return modal('<h2>Camera criogenica</h2><p>La porta è bloccata finché la rotta non è stabile.</p>');if(state.flags.cryo)return modal('<h2>Camera a gravità zero</h2><p>Il fusibile è già stato recuperato.</p>');if(!chosen('Gancio magnetico'))return modal('<h2>Camera a gravità zero</h2><p>Un fusibile galleggia oltre il vetro. Seleziona il Gancio magnetico.</p>');remove('Gancio magnetico');state.flags.cryo=true;state.step=4;add('Fusibile quantico','🔌');remember('Recuperato un fusibile quantico dalla camera a gravità zero.');render();modal('<h2>4. Recupero in gravità zero</h2><p>Il gancio attira il fusibile fuori dal condotto.</p>')}
function systems(){if(!state.flags.cryo)return modal('<h2>Console sistemi</h2><p>Manca il fusibile principale.</p>');if(state.flags.systems)return modal('<h2>Console sistemi</h2><p>Supporto vitale, comunicazioni e scudi sono attivi.</p>');if(!chosen('Fusibile quantico'))return modal('<h2>Console sistemi</h2><p>Seleziona il Fusibile quantico.</p>');remove('Fusibile quantico');eos.seq=[];modal('<h2>5. Riattivazione sistemi</h2><p>Avvia nell’ordine: supporto vitale, comunicazioni, scudi.</p><div class="eos-grid"><button data-es="V">O₂</button><button data-es="C">COM</button><button data-es="S">SCUDI</button><button data-es="N">NAV</button></div><p id="eosMsg"></p>');setTimeout(()=>q('#modalContent').querySelectorAll('[data-es]').forEach(b=>b.onclick=()=>{eos.seq.push(b.dataset.es);if(eos.seq.length===3){if(eos.seq.join('')==='VCS'){state.flags.systems=true;state.step=5;add('Scheda portellone','💳');remember('Sistemi riattivati: O₂ → COM → SCUDI.');render();q('#eosMsg').innerHTML='<span class="success">SISTEMI ONLINE</span>'}else{eos.seq=[];q('#eosMsg').innerHTML='<span class="error">Ordine errato.</span>'}}}),0)}
function cargo(){if(!state.flags.systems)return modal('<h2>Vano tecnico</h2><p>Il sistema di apertura non risponde.</p>');if(state.flags.cargo)return modal('<h2>Portellone tecnico</h2><p>La scheda è già installata.</p>');if(!chosen('Scheda portellone'))return modal('<h2>Portellone tecnico</h2><p>Seleziona la Scheda portellone.</p>');remove('Scheda portellone');state.flags.cargo=true;state.step=6;add('Checklist di lancio','📋');remember('Checklist: 2 → 5 → 1 → 4 → 3.');render();modal('<h2>6. Riparazione portellone</h2><p>La nuova scheda sblocca il vano del modulo di fuga.</p><div class="clue">CHECKLIST 2 → 5 → 1 → 4 → 3</div>')}
function launch(){if(!state.flags.cargo)return modal('<h2>Pannello di lancio</h2><p>Serve la checklist del vano tecnico.</p>');if(state.flags.launch)return modal('<h2>Pannello di lancio</h2><p>Sequenza armata.</p>');eos.seq=[];modal('<h2>7. Sequenza di lancio</h2><p>Premi gli interruttori secondo la checklist.</p><div class="eos-grid">${[1,2,3,4,5].map(n=>`<button data-el="${n}">${n}</button>`).join('')}</div><p id="eosMsg"></p>');setTimeout(()=>q('#modalContent').querySelectorAll('[data-el]').forEach(b=>b.onclick=()=>{eos.seq.push(b.dataset.el);if(eos.seq.length===5){if(eos.seq.join('')==='25143'){state.flags.launch=true;state.step=7;add('ID comandante','🪪');remember('Sequenza di lancio armata: 2–5–1–4–3.');render();q('#eosMsg').innerHTML='<span class="success">MODULO ARMATO</span>'}else{eos.seq=[];q('#eosMsg').innerHTML='<span class="error">Sequenza annullata.</span>'}}}),0)}
function hatch(){if(!state.flags.launch)return modal('<h2>Modulo di fuga</h2><p>La sequenza di lancio non è ancora armata.</p>');if(!chosen('ID comandante'))return modal('<h2>Modulo di fuga</h2><p>Seleziona l’ID comandante.</p>');modal('<h2>8. Avvio modulo di fuga</h2><p>Combina il numero dell’equipaggio con i minuti del risveglio.</p><div class="code-input"><input id="eosFinal" inputmode="numeric" maxlength="4" placeholder="0000"><button id="eosFinalBtn">LANCIA</button></div><p id="eosMsg"></p>');setTimeout(()=>q('#eosFinalBtn').onclick=()=>{if(q('#eosFinal').value==='7349'){state.flags.hatch=true;state.escaped=true;clearInterval(timerId);render();setTimeout(()=>{document.body.classList.remove('eos-active');q('.look-hint')?.style.removeProperty('display');finish()},500)}else q('#eosMsg').innerHTML='<span class="error">Codice comandante errato.</span>'},0)}
function install(){const play=q('#playBtn');if(!play)return;play.addEventListener('click',ev=>{if(!active())return;ev.preventDefault();ev.stopImmediatePropagation();start()},true)}
q('#hintBtn')?.addEventListener('click',ev=>{if(!active()||!document.body.classList.contains('eos-active'))return;ev.preventDefault();ev.stopImmediatePropagation();const h=['Reattore: 3–1–4.','Seleziona la Chiave dati.','Rotta: △ ○ □.','Usa il Gancio magnetico.','Ordine sistemi: O₂, COM, SCUDI.','Installa la scheda portellone.','Checklist: 2–5–1–4–3.','Codice finale: 7349.'];if(state.hints<=0)return modal('<h2>Indizi terminati</h2>');state.hints--;state.hintsUsed++;q('#hintCount').textContent=state.hints;modal(`<h2>Indizio</h2><p>${h[Math.min(state.step,7)]}</p>`)},true);
q('#notesBtn')?.addEventListener('click',ev=>{if(!active()||!document.body.classList.contains('eos-active'))return;ev.preventDefault();ev.stopImmediatePropagation();modal(`<h2>Appunti</h2>${state.notes.length?'<ul>'+state.notes.map(n=>`<li>${n}</li>`).join('')+'</ul>':'<p>Nessun appunto.</p>'}`)},true);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();