/* Profondità Zero V3 — motore dedicato, non derivato da Bunker Omega */
(() => {
  const $=s=>document.querySelector(s);
  const d={selected:null,sonar:[],ballast:[],route:[]};
  const has=n=>state?.inventory?.some(x=>x.name===n);
  const chosen=n=>d.selected===n&&has(n);
  const note=t=>{if(state&&!state.notes.includes(t))state.notes.push(t)};
  function add(name,icon){if(!has(name)){state.inventory.push({name,icon});inventory()}}
  function remove(name){state.inventory=state.inventory.filter(x=>x.name!==name);if(d.selected===name)d.selected=null;inventory()}
  function inventory(){const box=$('#inventoryItems');box.innerHTML=state.inventory.length?state.inventory.map(i=>`<button class="inventory-item depth3-inv ${d.selected===i.name?'selected':''}" data-d3-item="${i.name}"><span>${i.icon}</span>${i.name}</button>`).join(''):'<span class="empty">Vuoto</span>';box.querySelectorAll('[data-d3-item]').forEach(b=>b.onclick=()=>{d.selected=d.selected===b.dataset.d3Item?null:b.dataset.d3Item;inventory();status(d.selected?`${d.selected} selezionato`:'Oggetto deselezionato')})}
  function status(t){const e=$('.depth3-status');if(!e)return;e.textContent=t;clearTimeout(status.t);status.t=setTimeout(()=>e.textContent='Ferma la perdita, bilancia la zavorra e prepara la risalita',2600)}
  const hot=(c,label,done)=>`<button class="depth3-hot ${c} ${done?'solved':''}" data-d3="${c}" aria-label="${label}"><span>${label}</span></button>`;
  function scene(){const f=state.flags;document.body.classList.add('depth3-active');$('#sceneBackdrop').style.background='transparent';$('#sceneObjects').innerHTML=`<div class="depth3 ${f.balanced?'balanced':''} ${f.oxygen?'oxygen-ok':''} ${f.hatch?'hatch-open':''}"><div class="depth3-shell"></div><div class="depth3-window"><div class="depth3-seabed"></div><div class="depth3-lightcone"></div><div class="depth3-creature"></div><div class="depth3-crack"></div>${f.leakFixed?'':'<div class="depth3-leak"></div>'}</div><div class="depth3-toolbox"></div><div class="depth3-chart"></div><div class="depth3-console"><div class="depth3-screen left"><div class="depth3-radar"></div></div><div class="depth3-screen center"><div class="depth3-tanks"><i></i><i></i><i></i></div></div><div class="depth3-screen right"><div class="depth3-o2">${f.oxygen?'92%':'18%'}<small>${f.oxygen?'STABILE':'CRITICO'}</small></div></div></div><div class="depth3-wheel"></div><div class="depth3-hatch"><i></i></div>${hot('chart','Carta batimetrica',f.chart)}${hot('sonar','Sonar',f.sonar)}${hot('toolbox','Kit riparazione',f.toolbox)}${hot('leak','Perdita nella vetrata',f.leakFixed)}${hot('ballast','Controllo zavorra',f.balanced)}${hot('oxygen','Sistema ossigeno',f.oxygen)}${hot('wheel','Timone di emergenza',f.route)}${hot('hatch','Portello di risalita',f.hatch)}<div class="depth3-bubbles"></div><div class="depth3-vignette"></div><div class="depth3-status">Ferma la perdita, bilancia la zavorra e prepara la risalita</div></div>`;document.querySelectorAll('[data-d3]').forEach(b=>b.onclick=()=>inspect(b.dataset.d3))}
  function begin(){clearInterval(timerId);state={time:selected.minutes*60,hints:3,hintsUsed:0,step:0,inventory:[],notes:[],escaped:false,flags:{}};d.selected=null;d.sonar=[];d.ballast=[];d.route=[];$('#gameCase').textContent='CASO 06';$('#gameTitle').textContent='Profondità Zero';$('#hintCount').textContent=3;scene();inventory();updateTimer();show('game');setTimeout(()=>modal('<h2>Profondità Zero</h2><p>La cabina panoramica è incrinata. L’acqua entra, l’ossigeno è al 18% e una massa enorme gira attorno allo scafo.</p><p>Non devi aprire una semplice porta: devi rendere il sottomarino capace di risalire.</p><button id="d3start" class="action-btn">PRENDI IL CONTROLLO</button>'),70);setTimeout(()=>{const b=$('#d3start');if(b)b.onclick=closeModal},140);timerId=setInterval(()=>{if(state.time>0&&!state.escaped){state.time--;updateTimer()}else if(!state.escaped){clearInterval(timerId);modal('<h2>Ossigeno esaurito</h2><p>La cabina si spegne sul fondale.</p><button id="d3retry" class="action-btn">RIPROVA</button>');setTimeout(()=>{const b=$('#d3retry');if(b)b.onclick=()=>{closeModal();begin()}},0)}},1000)}
  function inspect(id){({chart,sonar,toolbox,leak,ballast,oxygen,wheel,hatch}[id]||(()=>{}))()}
  function chart(){if(state.flags.chart)return modal('<h2>Carta batimetrica</h2><p>Settore 52. Immersione registrata alle 04:37. Simboli di rotta: triangolo, cerchio, quadrato.</p>');state.flags.chart=true;state.step=1;add('Carta batimetrica','🗺️');note('Settore 52 — immersione 04:37 — rotta △ ○ □.');scene();modal('<h2>Carta batimetrica</h2><p>La carta non contiene un codice da digitare subito: mostra una rotta composta da tre simboli.</p><p class="tool-success">△ → ○ → □</p>')}
  function sonar(){if(state.flags.sonar)return modal('<h2>Sonar panoramico</h2><p>Il relitto utile è stato localizzato a 52 metri sulla sinistra.</p>');if(!has('Carta batimetrica'))return modal('<h2>Sonar panoramico</h2><p>Tre echi si sovrappongono. Serve una carta per distinguere la rotta corretta.</p>');modal('<h2>Sonar panoramico</h2><p>Segui i simboli indicati sulla carta.</p><div class="depth3-puzzle"><button data-d3sonar="T">△</button><button data-d3sonar="C">○</button><button data-d3sonar="Q">□</button></div><p id="d3sonarmsg"></p>');setTimeout(()=>document.querySelectorAll('[data-d3sonar]').forEach(b=>b.onclick=()=>{d.sonar.push(b.dataset.d3sonar);b.disabled=true;if(d.sonar.length===3){if(d.sonar.join('')==='TCQ'){state.flags.sonar=true;state.step=2;add('Coordinate relitto','📡');note('Il sonar localizza un contenitore tecnico a 52 metri, lato sinistro.');scene();$('#d3sonarmsg').innerHTML='<span class="success">CONTATTO LOCALIZZATO</span>'}else{d.sonar=[];document.querySelectorAll('[data-d3sonar]').forEach(x=>x.disabled=false);$('#d3sonarmsg').innerHTML='<span class="error">Rotta sonar errata.</span>'}}}),0)}
  function toolbox(){if(state.flags.toolbox)return modal('<h2>Kit di riparazione</h2><p>Hai già recuperato la resina pressurizzata.</p>');if(!has('Coordinate relitto'))return modal('<h2>Vano recupero</h2><p>Il braccio esterno non sa quale bersaglio agganciare.</p>');modal('<h2>Braccio di recupero</h2><p>Imposta la distanza del relitto individuato dal sonar.</p><div class="code-input"><input id="d3distance" inputmode="numeric" maxlength="2" placeholder="00"><button id="d3distancebtn">RECUPERA</button></div><p id="d3distmsg"></p>');setTimeout(()=>$('#d3distancebtn').onclick=()=>{if($('#d3distance').value==='52'){state.flags.toolbox=true;state.step=3;add('Resina pressurizzata','🧪');note('Recuperata resina pressurizzata dal relitto.');scene();$('#d3distmsg').innerHTML='<span class="success">CONTENITORE A BORDO</span>'}else $('#d3distmsg').innerHTML='<span class="error">Il braccio non trova nulla.</span>'},0)}
  function leak(){if(state.flags.leakFixed)return modal('<h2>Vetrata panoramica</h2><p>La crepa è sigillata. La pressione interna regge.</p>');if(!chosen('Resina pressurizzata'))return modal('<h2>Perdita nella vetrata</h2><p>L’acqua entra dalla crepa. Serve un materiale capace di indurire sotto pressione.</p>');remove('Resina pressurizzata');state.flags.leakFixed=true;state.step=4;add('Dati di pressione','🌊');note('Perdita sigillata. Pressioni serbatoi rilevate: 4, 3, 7.');scene();modal('<h2>Riparazione completata</h2><p>La resina sigilla la crepa. Il sistema ora riesce a misurare correttamente le tre cisterne.</p><p class="tool-success">SERBATOI: 4 — 3 — 7</p>')}
  function ballast(){if(state.flags.balanced)return modal('<h2>Zavorra</h2><p>Le tre cisterne sono bilanciate e la prua è libera dal fondale.</p>');if(!state.flags.leakFixed)return modal('<h2>Controllo zavorra</h2><p>Il sistema rifiuta lo scarico finché la cabina perde pressione.</p>');modal('<h2>Bilanciamento zavorra</h2><p>Scarica le cisterne dalla pressione più alta alla più bassa.</p><div class="depth3-puzzle"><button data-d3tank="4">4</button><button data-d3tank="3">3</button><button data-d3tank="7">7</button></div><p id="d3tankmsg"></p>');setTimeout(()=>document.querySelectorAll('[data-d3tank]').forEach(b=>b.onclick=()=>{d.ballast.push(b.dataset.d3tank);b.disabled=true;if(d.ballast.length===3){if(d.ballast.join('')==='743'){state.flags.balanced=true;state.step=5;add('Cella ossigeno','🔋');note('Zavorra bilanciata nell’ordine 7-4-3. Liberata una cella ossigeno.');scene();$('#d3tankmsg').innerHTML='<span class="success">ASSETTO ORIZZONTALE</span>'}else{d.ballast=[];document.querySelectorAll('[data-d3tank]').forEach(x=>x.disabled=false);$('#d3tankmsg').innerHTML='<span class="error">La cabina si inclina pericolosamente.</span>'}}}),0)}
  function oxygen(){if(state.flags.oxygen)return modal('<h2>Sistema ossigeno</h2><p>Livello stabile al 92%.</p>');if(!chosen('Cella ossigeno'))return modal('<h2>Sistema ossigeno</h2><p>La cartuccia è esaurita. Serve una nuova cella.</p>');remove('Cella ossigeno');state.flags.oxygen=true;state.step=6;add('Autorizzazione timone','🪪');note('Ossigeno ripristinato al 92%. Timone di emergenza autorizzato.');scene();modal('<h2>Ossigeno ripristinato</h2><p>La cabina torna respirabile e il timone di emergenza si illumina.</p>')}
  function wheel(){if(state.flags.route)return modal('<h2>Timone di emergenza</h2><p>Rotta di risalita già impostata: 04:37.</p>');if(!state.flags.oxygen)return modal('<h2>Timone di emergenza</h2><p>Il sistema non consente la manovra con ossigeno critico.</p>');modal('<h2>Rotta di risalita</h2><p>Inserisci l’ora dell’immersione riportata sulla carta.</p><div class="code-input"><input id="d3route" inputmode="numeric" maxlength="4" placeholder="0000"><button id="d3routebtn">IMPOSTA ROTTA</button></div><p id="d3routemsg"></p>');setTimeout(()=>$('#d3routebtn').onclick=()=>{if($('#d3route').value==='0437'){state.flags.route=true;state.step=7;add('Chiave di risalita','🔷');note('Rotta 04:37 caricata. Portello di risalita pronto.');scene();$('#d3routemsg').innerHTML='<span class="success">ROTTА CARICATA</span>'}else $('#d3routemsg').innerHTML='<span class="error">Rotta incompatibile.</span>'},0)}
  function hatch(){if(state.flags.hatch)return;if(!state.flags.route||!state.flags.balanced)return modal('<h2>Portello di risalita</h2><p>Il sottomarino non è ancora stabile o la rotta non è caricata.</p>');if(!chosen('Chiave di risalita'))return modal('<h2>Portello di risalita</h2><p>Seleziona la chiave di risalita dall’inventario.</p>');state.flags.hatch=true;scene();setTimeout(()=>{document.body.classList.remove('depth3-active');finish()},700)}
  function hint(){if(state.hints<=0)return modal('<h2>Nessun indizio rimasto</h2><p>Controlla carta, scena e inventario.</p>');const h=['Inizia dalla carta batimetrica sulla destra.','Sul sonar segui △, ○, □.','Il relitto è a distanza 52.','Seleziona la resina e tocca la crepa.','Scarica le cisterne dalla pressione maggiore: 7, 4, 3.','Seleziona la cella e ripristina l’ossigeno.','L’ora dell’immersione è 04:37.','Seleziona la chiave di risalita e apri il portello.'];state.hints--;state.hintsUsed++;$('#hintCount').textContent=state.hints;modal(`<h2>Indizio</h2><p>${h[Math.min(state.step,h.length-1)]}</p>`)}
  function isDepth(){return selected?.id==='sottomarino'}
  $('#playBtn').addEventListener('click',e=>{if(!isDepth())return;e.preventDefault();e.stopImmediatePropagation();begin()},true);
  $('#hintBtn').addEventListener('click',e=>{if(!isDepth()||!document.body.classList.contains('depth3-active'))return;e.preventDefault();e.stopImmediatePropagation();hint()},true);
  $('#notesBtn').addEventListener('click',e=>{if(!isDepth()||!document.body.classList.contains('depth3-active'))return;e.preventDefault();e.stopImmediatePropagation();modal(`<h2>Appunti</h2>${state.notes.length?'<ul>'+state.notes.map(n=>`<li>${n}</li>`).join('')+'</ul>':'<p>Non hai ancora scoperto nulla.</p>'}`)},true);
  $('#exitBtn').addEventListener('click',()=>document.body.classList.remove('depth3-active'),true);
})();
