/* Profondità Zero V2 — stanza dedicata */
(() => {
  const $=s=>document.querySelector(s);
  const sea={selected:null,sonar:[],valves:[]};
  const oldPlay=$('#playBtn').onclick,oldHint=$('#hintBtn').onclick,oldNotes=$('#notesBtn').onclick,oldExit=$('#exitBtn').onclick;
  const has=n=>state&&state.inventory.some(x=>x.name===n);
  const chosen=n=>sea.selected===n&&has(n);
  const add=(name,icon)=>{if(!has(name))state.inventory.push({name,icon});drawInventory();};
  const remove=name=>{state.inventory=state.inventory.filter(x=>x.name!==name);if(sea.selected===name)sea.selected=null;drawInventory();};
  const note=t=>{if(state&&!state.notes.includes(t))state.notes.push(t);};
  function drawInventory(){const b=$('#inventoryItems');b.innerHTML=state.inventory.length?state.inventory.map(i=>`<button class="inventory-item depth-inv ${sea.selected===i.name?'selected':''}" data-depth-item="${i.name}"><span>${i.icon}</span>${i.name}</button>`).join(''):'<span class="empty">Vuoto</span>';b.querySelectorAll('[data-depth-item]').forEach(x=>x.onclick=()=>{sea.selected=sea.selected===x.dataset.depthItem?null:x.dataset.depthItem;drawInventory();status(sea.selected?`${sea.selected} selezionato`:'Oggetto deselezionato');});}
  function status(t){const e=$('.depth-status');if(!e)return;e.textContent=t;clearTimeout(status.t);status.t=setTimeout(()=>e.textContent='Ripristina ossigeno e riporta il sottomarino in superficie',2500);}
  const hot=(id,label,done)=>`<button class="depth-hot depth-hit-${id} ${done?'solved':''}" data-depth="${id}" aria-label="${label}"><span>${label}</span></button>`;
  function drawScene(){const f=state.flags;document.body.classList.add('depth-active');$('#sceneBackdrop').style.background='transparent';$('#sceneObjects').innerHTML=`<div class="depth-scene ${f.power?'power-on':''} ${f.oxygen?'oxygen-on':''} ${f.hatch?'hatch-open':''}"><div class="depth-wall"></div><div class="depth-floor"></div><div class="depth-window"><div class="depth-creature"></div></div><div class="depth-sonar"><i></i><b>SONAR</b></div><div class="depth-clock">04:37</div><div class="depth-safe"><span>SETTORE 52</span></div><div class="depth-panel"><b>ENERGIA</b><i></i><i></i><i></i></div><div class="depth-valves"><i></i><i></i><i></i></div><div class="depth-console"><span>ASSETTO</span><div></div></div><div class="depth-hatch"><div class="wheel"></div></div><div class="depth-oxygen">O₂ ${f.oxygen?'STABILE':'18%'}</div>${hot('sonar','Sonar',f.sonar)}${hot('clock','Orologio di bordo',f.clock)}${hot('safe','Cassaforte',f.safe)}${hot('panel','Quadro elettrico',f.panel)}${hot('valves','Valvole',f.valves)}${hot('console','Console di assetto',f.console)}${hot('hatch','Camera stagna',f.hatch)}<div class="depth-bubbles"></div><div class="depth-vignette"></div><div class="depth-status">Ripristina ossigeno e riporta il sottomarino in superficie</div></div>`;document.querySelectorAll('[data-depth]').forEach(b=>b.onclick=()=>inspect(b.dataset.depth));}
  function begin(){clearInterval(timerId);state={time:selected.minutes*60,hints:3,hintsUsed:0,step:0,inventory:[],notes:[],escaped:false,flags:{}};sea.selected=null;sea.sonar=[];sea.valves=[];$('#gameCase').textContent='CASO 06';$('#gameTitle').textContent='Profondità Zero';$('#hintCount').textContent=3;drawScene();drawInventory();updateTimer();show('game');setTimeout(()=>modal('<h2>Profondità Zero</h2><p>Il sottomarino giace sul fondale. L’ossigeno cala e il sonar rileva qualcosa all’esterno.</p><button id="depthStart" class="action-btn">ENTRA NELLA SALA DI CONTROLLO</button>'),80);setTimeout(()=>{const b=$('#depthStart');if(b)b.onclick=closeModal},150);timerId=setInterval(()=>{if(state.time>0&&!state.escaped){state.time--;updateTimer()}else if(!state.escaped){clearInterval(timerId);modal('<h2>Tempo scaduto</h2><p>L’ossigeno si esaurisce e le luci si spengono.</p><button id="depthRetry" class="action-btn">RIPROVA</button>');setTimeout(()=>{const b=$('#depthRetry');if(b)b.onclick=()=>{closeModal();begin()}},0)}},1000);}
  function inspect(id){({sonar,clock,safe,panel,valves,console:balance,hatch}[id]||(()=>{}))();}
  function sonar(){if(state.flags.sonar)return modal('<h2>Sonar</h2><p>Il segnale indica immersione 04:37, settore 52.</p>');modal('<h2>Sonar</h2><p>Allinea i tre impulsi nella sequenza breve-lungo-breve.</p><div class="depth-puzzle">${[['B','•'],['L','—'],['B','•']].map(x=>`<button data-sonar="${x[0]}">${x[1]}</button>`).join('')}</div><p id="depthMsg"></p>');setTimeout(()=>document.querySelectorAll('[data-sonar]').forEach(b=>b.onclick=()=>{sea.sonar.push(b.dataset.sonar);b.disabled=true;if(sea.sonar.length===3){if(sea.sonar.join('')==='BLB'){state.flags.sonar=true;state.step=1;add('Diario di bordo','📘');note('Diario: immersione 04:37, settore 52.');drawScene();$('#depthMsg').innerHTML='<span class="success">TRACCIA DECODIFICATA</span>'}else{sea.sonar=[];document.querySelectorAll('[data-sonar]').forEach(x=>x.disabled=false);$('#depthMsg').innerHTML='<span class="error">Eco non riconosciuto.</span>'}}}),0);}
  function clock(){if(state.flags.clock)return modal('<h2>Orologio</h2><p>È sincronizzato sulle 04:37.</p>');if(!has('Diario di bordo'))return modal('<h2>Orologio</h2><p>Manca il riferimento temporale.</p>');modal('<h2>Orologio di bordo</h2><p>Inserisci l’orario dell’immersione.</p><div class="code-input"><input id="depthClock" inputmode="numeric" maxlength="4" placeholder="0000"><button id="depthClockBtn">SINCRONIZZA</button></div><p id="depthClockMsg"></p>');setTimeout(()=>$('#depthClockBtn').onclick=()=>{if($('#depthClock').value==='0437'){state.flags.clock=true;state.step=2;add('Chiave nautica','🗝️');note('L’orologio libera una chiave nautica.');drawScene();$('#depthClockMsg').innerHTML='<span class="success">SINCRONIZZATO</span>'}else $('#depthClockMsg').innerHTML='<span class="error">Orario errato.</span>'},0);}
  function safe(){if(state.flags.safe)return modal('<h2>Cassaforte</h2><p>È già aperta.</p>');if(!chosen('Chiave nautica'))return modal('<h2>Cassaforte</h2><p>Richiede una chiave nautica.</p>');remove('Chiave nautica');state.flags.safe=true;state.step=3;add('Schema valvole','📋');note('Settore 52: valvole sinistra, centro, destra.');drawScene();modal('<h2>Cassaforte</h2><p>Trovi lo schema del circuito di zavorra.</p><p class="tool-success">SINISTRA → CENTRO → DESTRA</p>');}
  function panel(){if(state.flags.panel)return modal('<h2>Quadro elettrico</h2><p>L’alimentazione è attiva.</p>');if(!has('Schema valvole'))return modal('<h2>Quadro elettrico</h2><p>Tre interruttori sono fuori fase.</p>');modal('<h2>Quadro elettrico</h2><p>Attiva gli interruttori 5, 2, 4.</p><div class="depth-puzzle">${['2','4','5'].map(n=>`<button data-switch="${n}">${n}</button>`).join('')}</div><p id="depthSwitchMsg"></p>');setTimeout(()=>document.querySelectorAll('[data-switch]').forEach(b=>b.onclick=()=>{sea.valves.push(b.dataset.switch);b.disabled=true;if(sea.valves.length===3){if(sea.valves.join('')==='524'){state.flags.panel=true;state.flags.power=true;state.step=4;add('Manovella','⚙️');note('Il quadro riparte e libera una manovella.');drawScene();$('#depthSwitchMsg').innerHTML='<span class="success">ENERGIA RIPRISTINATA</span>'}else{sea.valves=[];document.querySelectorAll('[data-switch]').forEach(x=>x.disabled=false);$('#depthSwitchMsg').innerHTML='<span class="error">Sovraccarico evitato.</span>'}}}),0);}
  function valves(){if(state.flags.valves)return modal('<h2>Valvole</h2><p>La zavorra è stabilizzata.</p>');if(!chosen('Manovella'))return modal('<h2>Valvole</h2><p>Serve una manovella per ruotarle.</p>');modal('<h2>Valvole di zavorra</h2><p>Imposta sinistra, centro, destra.</p><div class="depth-puzzle"><button data-valve="S">←</button><button data-valve="C">•</button><button data-valve="D">→</button></div><p id="depthValveMsg"></p>');setTimeout(()=>document.querySelectorAll('[data-valve]').forEach(b=>b.onclick=()=>{sea.sonar.push(b.dataset.valve);if(sea.sonar.slice(-3).join('')==='SCD'){remove('Manovella');state.flags.valves=true;state.step=5;add('Scheda sonar','💳');note('Le valvole liberano la scheda sonar.');drawScene();$('#depthValveMsg').innerHTML='<span class="success">ZAVORRA STABILE</span>'}else if(sea.sonar.length>=3){sea.sonar=[];$('#depthValveMsg').innerHTML='<span class="error">Sequenza errata.</span>'}}),0);}
  function balance(){if(state.flags.console)return modal('<h2>Console</h2><p>Assetto e ossigeno sono stabili.</p>');if(!state.flags.power||!has('Scheda sonar'))return modal('<h2>Console di assetto</h2><p>Richiede energia e scheda sonar.</p>');modal('<h2>Console di assetto</h2><p>Inserisci settore e ultime due cifre dell’orario.</p><div class="code-input"><input id="depthBalance" inputmode="numeric" maxlength="4" placeholder="0000"><button id="depthBalanceBtn">ESEGUI</button></div><p id="depthBalanceMsg"></p>');setTimeout(()=>$('#depthBalanceBtn').onclick=()=>{if($('#depthBalance').value==='5237'){state.flags.console=true;state.flags.oxygen=true;state.step=6;add('Badge camera stagna','🪪');note('Codice 5237 accettato. Ossigeno ripristinato.');drawScene();$('#depthBalanceMsg').innerHTML='<span class="success">RISALITA AUTORIZZATA</span>'}else $('#depthBalanceMsg').innerHTML='<span class="error">Dati non validi.</span>'},0);}
  function hatch(){if(state.flags.hatch)return;if(!state.flags.oxygen)return modal('<h2>Camera stagna</h2><p>La pressione non è ancora sicura.</p>');if(!chosen('Badge camera stagna'))return modal('<h2>Camera stagna</h2><p>Seleziona il badge di accesso.</p>');state.flags.hatch=true;drawScene();document.body.classList.remove('depth-active');finish();}
  function hint(){if(state.hints<=0)return modal('<h2>Nessun indizio rimasto</h2><p>Controlla appunti e inventario.</p>');const h=['Il sonar usa breve, lungo, breve.','L’orario è 04:37.','Seleziona la chiave per la cassaforte.','Il quadro segue 5-2-4.','Seleziona la manovella e usa sinistra-centro-destra.','Il codice console è 52 seguito da 37.','Seleziona il badge e apri la camera stagna.'];state.hints--;state.hintsUsed++;$('#hintCount').textContent=state.hints;modal(`<h2>Indizio</h2><p>${h[Math.min(state.step,h.length-1)]}</p>`);}
  $('#playBtn').onclick=()=>selected&&selected.id==='sottomarino'?begin():oldPlay();
  $('#hintBtn').onclick=()=>selected&&selected.id==='sottomarino'?hint():oldHint();
  $('#notesBtn').onclick=()=>selected&&selected.id==='sottomarino'?modal(`<h2>Appunti</h2>${state.notes.length?'<ul>'+state.notes.map(n=>`<li>${n}</li>`).join('')+'</ul>':'<p>Non hai ancora scoperto nulla.</p>'}`):oldNotes();
  $('#exitBtn').onclick=()=>{document.body.classList.remove('depth-active');oldExit();};
})();