const $=s=>document.querySelector(s);
const rooms=[
{id:'archivio47',order:1,title:'Archivio 47',icon:'🗄️',theme:'mistero',difficulty:'easy',minutes:15,puzzles:4,case:'CASO 01',story:'Ti risvegli in un archivio sotterraneo. La porta è bloccata e un registratore ripete: “Non cercare la chiave. Cerca ciò che la chiave ricorda.”',colors:['#27303b','#17120f','#9d343b'],objects:['📚','🕰️','🗄️','▥','🚪'],names:['Scaffale 7','Orologio fermo','Scrivania','Grata','Porta blindata'],clue:'Una fotografia riporta: “Il tempo si fermò alle 10:10. Fascicolo 47.”',codes:['1010','47','4710'],items:[['Foto strappata','📷'],['Chiave piccola','🗝️'],['Cacciavite','🪛'],['Tessera','💳']],ending:'La porta si apre. Nel corridoio trovi un fascicolo con scritto CASO 48.'},
{id:'motel13',order:2,title:'Motel 13',icon:'🏨',theme:'horror',difficulty:'easy',minutes:15,puzzles:4,case:'CASO 02',story:'La stanza 13 non compare nella planimetria. Il telefono squilla, ma dall’altro lato senti soltanto il rumore della pioggia.',colors:['#33231f','#130d0d','#a44435'],objects:['🖼️','☎️','🧳','🪞','🚪'],names:['Quadro storto','Telefono','Valigia','Specchio','Porta'],clue:'Dietro il quadro: “La chiamata arrivò alle 23:16. Camera 13.”',codes:['2316','13','1316'],items:[['Biglietto','📝'],['Chiave valigia','🗝️'],['Frammento','🔺'],['Tessera motel','🎫']],ending:'La reception è vuota. Tutte le chiavi oscillano, tranne quella della stanza 13.'},
{id:'laboratorio',order:3,title:'Protocollo X',icon:'🧪',theme:'fantascienza',difficulty:'easy',minutes:15,puzzles:4,case:'CASO 03',story:'Un laboratorio automatico ha avviato la sterilizzazione. Hai pochi minuti per interrompere il protocollo e uscire.',colors:['#183539','#09171b','#2e9ca0'],objects:['📋','🧫','🔬','🧰','🚨'],names:['Registro','Incubatore','Microscopio','Armadietto','Uscita'],clue:'Registro tecnico: “Campione 08 stabilizzato alle 14:25.”',codes:['1425','08','0825'],items:[['Registro','📋'],['Chiave sterile','🔑'],['Fusibile','🔌'],['Badge','🪪']],ending:'Il protocollo si arresta a un secondo dalla chiusura. Sul monitor compare: SOGGETTO IDONEO.'},
{id:'museo',order:4,title:'Il Museo Silenzioso',icon:'🏛️',theme:'mistero',difficulty:'medium',minutes:22,puzzles:4,case:'CASO 04',story:'Durante il turno notturno una statua è scomparsa. Le porte si sono chiuse e il sistema ti considera l’intruso.',colors:['#2d2a24','#12100d','#9e7d3d'],objects:['🗿','🕯️','🗺️','🧰','🚪'],names:['Statua','Candelabro','Mappa','Vetrina','Portone'],clue:'Sulla base: “Restauro 19:42, reperto 26.”',codes:['1942','26','2642'],items:[['Targhetta','🏷️'],['Chiave antica','🗝️'],['Sigillo','🔘'],['Pass custode','🎟️']],ending:'Il portone si apre. La statua scomparsa è ora alle tue spalle.'},
{id:'bunker',order:5,title:'Bunker Omega',icon:'☢️',theme:'avventura',difficulty:'medium',minutes:24,puzzles:4,case:'CASO 05',story:'Una trasmissione d’emergenza riattiva un bunker abbandonato. Il conto alla rovescia nucleare è già iniziato.',colors:['#30331e','#111309','#8f9d30'],objects:['📻','⏱️','🗄️','🛠️','🚧'],names:['Radio','Cronometro','Archivio','Quadro elettrico','Portello'],clue:'La radio scandisce: “Codice squadra 31. Sincronizzazione 06:18.”',codes:['0618','31','3118'],items:[['Trascrizione','📄'],['Chiave bunker','🔑'],['Leva','🕹️'],['Carta comando','💳']],ending:'Il portello cede. La trasmissione riparte: “Omega non era il bunker. Era tu.”'},
{id:'sottomarino',order:6,title:'Profondità Zero',icon:'⚓',theme:'avventura',difficulty:'medium',minutes:25,puzzles:4,case:'CASO 06',story:'Il sottomarino è immobile sul fondale. L’ossigeno diminuisce e l’equipaggio è svanito senza lasciare tracce.',colors:['#102d3d','#07131d','#247da2'],objects:['🧭','🕰️','🧰','🔧','🚪'],names:['Bussola','Orologio di bordo','Cassaforte','Valvola','Camera stagna'],clue:'Diario: “Immersione 04:37. Settore 52.”',codes:['0437','52','5237'],items:[['Diario','📘'],['Chiave nautica','🗝️'],['Manovella','⚙️'],['Scheda sonar','💳']],ending:'La camera stagna si apre. Fuori dal vetro, qualcosa di enorme si muove nel buio.'},
{id:'tempio',order:7,title:'Tempio del Sole Nero',icon:'🗿',theme:'avventura',difficulty:'hard',minutes:30,puzzles:4,case:'CASO 07',story:'Un passaggio si chiude dietro di te. Le pareti del tempio iniziano a muoversi e il sole nero sta per sorgere.',colors:['#40311d','#171006','#bd7730'],objects:['📜','☀️','🗿','⚱️','🚪'],names:['Pergamena','Disco solare','Idolo','Urna','Portale'],clue:'La pergamena indica: “Eclissi 17:33. Dinastia 64.”',codes:['1733','64','6433'],items:[['Pergamena','📜'],['Occhio di pietra','🔶'],['Scalpello','⛏️'],['Medaglione','🏅']],ending:'Il portale si apre mentre il tempio crolla. Il medaglione, però, continua a pulsare.'},
{id:'astronave',order:8,title:'Nave Eos',icon:'🚀',theme:'fantascienza',difficulty:'hard',minutes:32,puzzles:4,case:'CASO 08',story:'Ti svegli dal criosonno. La nave Eos è fuori rotta e l’intelligenza di bordo non riconosce più l’equipaggio.',colors:['#18213d','#090d1e','#566fca'],objects:['💻','🪐','🧊','🔧','🚪'],names:['Terminale','Mappa stellare','Capsula','Nucleo','Camera di fuga'],clue:'Log di rotta: “Risveglio 02:49. Equipaggio 73.”',codes:['0249','73','7349'],items:[['Log dati','💾'],['Chiave quantica','🔷'],['Cella energia','🔋'],['ID comandante','🪪']],ending:'La capsula parte. Eos corregge la rotta da sola e punta verso la Terra.'},
{id:'prigione',order:9,title:'Blocco K',icon:'⛓️',theme:'mistero',difficulty:'hard',minutes:34,puzzles:4,case:'CASO 09',story:'Sei rinchiuso nel Blocco K senza sapere perché. Ogni guardia è scomparsa e le telecamere continuano a seguirti.',colors:['#292c31','#0e1014','#636d75'],objects:['📰','🕰️','🔒','🔨','🚪'],names:['Giornale','Orologio','Armadietto','Muro debole','Cancello'],clue:'Sul giornale: “Rivolta alle 21:05. Detenuto 88.”',codes:['2105','88','8805'],items:[['Ritaglio','📰'],['Chiave cella','🗝️'],['Martello','🔨'],['Badge guardia','🪪']],ending:'Il cancello si apre. Nel registro scopri che il detenuto 88 porta il tuo nome.'},
{id:'hotel',order:10,title:'Hotel delle Ombre',icon:'🛎️',theme:'horror',difficulty:'nightmare',minutes:40,puzzles:4,case:'CASO 10',story:'L’ascensore si apre su un piano inesistente. Le porte delle camere respirano e il campanello suona da solo.',colors:['#341b2a','#12080e','#8c2f66'],objects:['📖','🛎️','🧳','🕯️','🚪'],names:['Registro ospiti','Campanello','Baule','Corridoio buio','Ascensore'],clue:'Ultima firma: “Arrivo 00:44. Ospite 99.”',codes:['0044','99','9944'],items:[['Pagina strappata','📖'],['Chiave 99','🗝️'],['Candela nera','🕯️'],['Gettone ascensore','🪙']],ending:'L’ascensore scende. Il display continua oltre il piano terra: −1, −2, −3…'},
{id:'navefantasma',order:11,title:'La Nave Senza Nome',icon:'🏴‍☠️',theme:'horror',difficulty:'nightmare',minutes:42,puzzles:4,case:'CASO 11',story:'Una nave emerge dalla nebbia. Appena sali a bordo, la costa scompare e le vele si spiegano senza vento.',colors:['#17302f','#071211','#287b70'],objects:['📜','🧭','⚰️','⚓','🚪'],names:['Diario del capitano','Bussola','Baule','Argano','Cabina'],clue:'Diario: “Ultimo avvistamento 03:27. Rotta 66.”',codes:['0327','66','6627'],items:[['Diario bagnato','📜'],['Chiave d’osso','🦴'],['Gancio','🪝'],['Medaglione pirata','☠️']],ending:'La cabina si apre. Al timone c’è una figura con il tuo stesso volto.'},
{id:'culto',order:12,title:'Il Cerchio',icon:'🔻',theme:'horror',difficulty:'nightmare',minutes:45,puzzles:5,case:'CASO 12',story:'Sotto una cappella abbandonata scopri una sala rituale. Il cerchio è incompleto e qualcuno sta tornando.',colors:['#30151a','#100608','#8d1f29'],objects:['📕','⏳','🗝️','🩸','🚪'],names:['Libro rituale','Clessidra','Reliquiario','Altare','Porta del cerchio'],clue:'Il libro recita: “Rito 11:59. Sigillo 77.”',codes:['1159','77','7759'],items:[['Pagina rituale','📕'],['Chiave cremisi','🗝️'],['Pugnale spento','🗡️'],['Sigillo','🔻']],ending:'Il cerchio si spezza e la porta si apre. Dall’altra parte non c’è l’esterno, ma la stanza da cui eri partito.'}
];
const difficultyMap={easy:['FACILE','green'],medium:['INTERMEDIO','yellow'],hard:['DIFFICILE','red'],nightmare:['INCUBO','purple']};
let progress=JSON.parse(localStorage.getItem('escapeProgress')||'{}');
let selected=null,state=null,timerId=null,sound=true;
function show(id){['home','briefing','game','ending'].forEach(x=>$('#'+x).classList.toggle('active',x===id));window.scrollTo(0,0)}
function saveProgress(){localStorage.setItem('escapeProgress',JSON.stringify(progress))}
function unlocked(room){return room.order===1||progress[rooms[room.order-2]?.id]?.completed}
function card(room){const p=progress[room.id]||{},lock=!unlocked(room),stars=p.stars||0;return `<article class="room-card" data-id="${room.id}" data-theme="${room.theme}" style="--cover1:${room.colors[0]};--cover2:${room.colors[1]};--glow:${room.colors[2]}"><div class="room-cover">${room.icon}</div><div class="room-card-content"><h3>${room.title}</h3><p>${room.story.slice(0,74)}…</p><div class="room-card-footer"><span>⏱ ${room.minutes} min</span><span class="stars-mini">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</span></div></div>${lock?'<div class="locked">🔒</div>':''}</article>`}
function renderRooms(){const groups={easy:$('#easyRooms'),medium:$('#mediumRooms'),hard:$('#hardRooms'),nightmare:$('#nightmareRooms')};Object.values(groups).forEach(x=>x.innerHTML='');rooms.forEach(r=>groups[r.difficulty].insertAdjacentHTML('beforeend',card(r)));document.querySelectorAll('.room-card').forEach(c=>c.onclick=()=>openBriefing(c.dataset.id));const done=Object.values(progress).filter(x=>x.completed).length;$('#completedCount').textContent=done;$('#totalStars').textContent=Object.values(progress).reduce((a,x)=>a+(x.stars||0),0)}
function openBriefing(id){const room=rooms.find(r=>r.id===id);if(!unlocked(room))return modal('<h2>Stanza bloccata</h2><p>Completa la stanza precedente per sbloccare questa esperienza.</p>');selected=room;const [label,cls]=difficultyMap[room.difficulty];$('#briefingDifficulty').textContent=label;$('#briefingDifficulty').className='level '+cls;$('#briefingIcon').textContent=room.icon;$('#briefingTitle').textContent=room.title;$('#briefingStory').textContent=room.story;$('#briefingTime').textContent=room.minutes;$('#briefingPuzzles').textContent=room.puzzles;$('#briefingBest').textContent=progress[id]?.best||'—';const bg=$('#briefingBg');bg.style.setProperty('--cover1',room.colors[0]);bg.style.setProperty('--glow',room.colors[2]);show('briefing')}
function freshState(){return{time:selected.minutes*60,hints:selected.difficulty==='nightmare'?1:3,hintsUsed:0,step:0,inventory:[],notes:[],escaped:false}}
function startGame(){state=freshState();clearInterval(timerId);$('#gameCase').textContent=selected.case;$('#gameTitle').textContent=selected.title;$('#hintCount').textContent=state.hints;const bg=$('#sceneBackdrop');bg.style.setProperty('--cover1',selected.colors[0]);bg.style.setProperty('--cover2',selected.colors[1]);bg.style.setProperty('--glow',selected.colors[2]);renderObjects();renderInventory();updateTimer();show('game');timerId=setInterval(()=>{if(state.time>0&&!state.escaped){state.time--;updateTimer()}else if(!state.escaped){clearInterval(timerId);modal(`<h2>Tempo scaduto</h2><p>La stanza ha vinto questa volta.</p><button class="action-btn" onclick="startGame();closeModal()">Riprova</button>`) }},1000)}
function renderObjects(){$('#sceneObjects').innerHTML=selected.objects.map((o,i)=>`<button class="object-btn" data-i="${i}" aria-label="${selected.names[i]}">${o}</button>`).join('');document.querySelectorAll('.object-btn').forEach(b=>b.onclick=()=>inspect(+b.dataset.i))}
function renderInventory(){$('#inventoryItems').innerHTML=state.inventory.length?state.inventory.map(i=>`<div class="inventory-item"><span>${i.icon}</span>${i.name}</div>`).join(''):'<span class="empty">Vuoto</span>'}
function addItem(index){const [name,icon]=selected.items[index];if(!state.inventory.some(x=>x.name===name)){state.inventory.push({name,icon});renderInventory()}}
function inspect(i){if(i===0)return firstClue();if(i===1)return firstLock();if(i===2)return secondLock();if(i===3)return toolPoint();if(i===4)return finalDoor()}
function firstClue(){if(state.step<1){state.step=1;state.notes.push(selected.clue);addItem(0)}modal(`<h2>${selected.names[0]}</h2><div class="object-art">${selected.objects[0]}</div><p>Trovi un dettaglio che qualcuno ha cercato di nascondere.</p><div class="clue">${selected.clue}</div>`)}
function codeModal(title,icon,text,code,onSuccess,max=4){modal(`<h2>${title}</h2><div class="object-art">${icon}</div><p>${text}</p><div class="code-input"><input id="codeValue" inputmode="numeric" maxlength="${max}" placeholder="${'0'.repeat(max)}"><button id="tryCode">PROVA</button></div><div id="codeMsg"></div>`);setTimeout(()=>$('#tryCode').onclick=()=>{if($('#codeValue').value===code){onSuccess();$('#codeMsg').innerHTML='<p class="success">Codice corretto. Un meccanismo si sblocca.</p>'}else $('#codeMsg').innerHTML='<p class="error">Codice errato.</p>'},0)}
function firstLock(){if(state.step<1)return modal(`<h2>${selected.names[1]}</h2><div class="object-art">${selected.objects[1]}</div><p>Manca un’indicazione per capire il codice.</p>`);if(state.step>=2)return modal(`<h2>${selected.names[1]}</h2><p>Il vano è già stato aperto.</p>`);codeModal(selected.names[1],selected.objects[1],'Usa l’orario trovato nell’indizio, senza i due punti.',selected.codes[0],()=>{state.step=2;addItem(1)})}
function secondLock(){if(state.step<2)return modal(`<h2>${selected.names[2]}</h2><div class="object-art">${selected.objects[2]}</div><p>È chiuso. Serve prima ciò che si nasconde nel secondo oggetto.</p>`);if(state.step>=3)return modal(`<h2>${selected.names[2]}</h2><p>Non è rimasto altro.</p>`);codeModal(selected.names[2],selected.objects[2],'Inserisci il numero principale citato nell’indizio.',selected.codes[1],()=>{state.step=3;addItem(2)},2)}
function toolPoint(){if(state.step<3)return modal(`<h2>${selected.names[3]}</h2><div class="object-art">${selected.objects[3]}</div><p>Non riesci a interagire senza lo strumento giusto.</p>`);if(state.step<4){state.step=4;addItem(3)}modal(`<h2>${selected.names[3]}</h2><div class="object-art">${selected.objects[3]}</div><p class="success">Usi lo strumento trovato e recuperi l’ultimo oggetto necessario per la fuga.</p>`)}
function finalDoor(){if(state.step<4)return modal(`<h2>${selected.names[4]}</h2><div class="object-art">${selected.objects[4]}</div><p>Il sistema non è ancora pronto. Esamina il resto della stanza.</p>`);codeModal(selected.names[4],selected.objects[4],'Combina il numero principale con le ultime due cifre dell’orario.',selected.codes[2],finish)}
function finish(){state.escaped=true;clearInterval(timerId);closeModal();const ratio=state.time/(selected.minutes*60);const stars=state.hintsUsed===0&&ratio>.35?3:state.hintsUsed<=1?2:1;const elapsed=selected.minutes*60-state.time;const best=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(elapsed%60).padStart(2,'0')}`;const old=progress[selected.id]||{};progress[selected.id]={completed:true,stars:Math.max(stars,old.stars||0),best:old.best&&old.best<best?old.best:best};saveProgress();$('#endingIcon').textContent=selected.icon;$('#endingTitle').textContent=selected.title+' completata';$('#endingText').textContent=selected.ending;$('#earnedStars').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);$('#finalTime').textContent=formatTime(state.time);$('#finalHints').textContent=state.hintsUsed;renderRooms();show('ending')}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function updateTimer(){$('#timer').textContent=formatTime(state.time)}
function modal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
function hint(){if(state.hints<=0)return modal('<h2>Nessun indizio rimasto</h2><p>Rileggi gli appunti e controlla gli oggetti nell’ordine giusto.</p>');const hints=['Inizia dall’oggetto in alto a sinistra: contiene l’indizio principale.','Usa l’orario senza i due punti sul secondo oggetto.','Il numero principale apre il terzo oggetto.','Lo strumento ottenuto serve sul quarto oggetto.','Il codice finale unisce numero e ultime due cifre dell’orario.'];state.hints--;state.hintsUsed++;$('#hintCount').textContent=state.hints;modal(`<h2>Indizio</h2><p>${hints[Math.min(state.step,hints.length-1)]}</p>`)}
function nextRoom(){const next=rooms.find(r=>r.order===selected.order+1);if(next)openBriefing(next.id);else show('home')}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;document.querySelectorAll('.room-card').forEach(c=>c.classList.toggle('hidden-card',f!=='all'&&c.dataset.theme!==f))});
$('#backHome').onclick=()=>show('home');$('#playBtn').onclick=startGame;$('#exitBtn').onclick=()=>modal('<h2>Uscire dalla stanza?</h2><p>I progressi della partita attuale andranno persi.</p><button id="confirmExit" class="action-btn">Esci</button>');document.addEventListener('click',e=>{if(e.target.id==='confirmExit'){clearInterval(timerId);closeModal();show('home')}});$('#hintBtn').onclick=hint;$('#notesBtn').onclick=()=>modal(`<h2>Appunti</h2><p>${state.notes.length?state.notes.map(x=>'• '+x).join('<br>'):'Non hai ancora trovato indizi.'}</p>`);$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'🔊 Audio':'🔇 Audio'};$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('#nextRoomBtn').onclick=nextRoom;$('#endingHomeBtn').onclick=()=>show('home');$('#profileBtn').onclick=()=>modal(`<h2>I tuoi progressi</h2><p>Stanze completate: <strong>${Object.values(progress).filter(x=>x.completed).length}/${rooms.length}</strong></p><p>Stelle raccolte: <strong>${Object.values(progress).reduce((a,x)=>a+(x.stars||0),0)}</strong></p>`);
renderRooms();