(()=>{
const q=s=>document.querySelector(s);let timer=null,startAt=0,remaining=15*60,selected=null,audioOn=true;
const state={step:0,hints:3,notes:[],items:[],flags:{},sequence:[],sub:0};
const show=id=>{document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));window.scrollTo(0,0)};
const modal=html=>{q('#modalContent').innerHTML=html;q('#modal').classList.remove('hidden')};
const close=()=>q('#modal').classList.add('hidden');
const remember=t=>{if(!state.notes.includes(t))state.notes.push(t)};
const has=n=>state.items.some(i=>i.name===n),chosen=n=>selected===n&&has(n);
function add(name,icon){if(!has(name))state.items.push({name,icon});renderInventory()}
function remove(name){state.items=state.items.filter(i=>i.name!==name);if(selected===name)selected=null;renderInventory()}
function renderInventory(){const b=q('#items');b.innerHTML=state.items.length?state.items.map(i=>`<button class="item ${selected===i.name?'selected':''}" data-item="${i.name}"><span>${i.icon}</span>${i.name}</button>`).join(''):'<span style="color:#69737f">Vuoto</span>';b.querySelectorAll('[data-item]').forEach(x=>x.onclick=()=>{selected=selected===x.dataset.item?null:x.dataset.item;renderInventory()})}
function hot(id,done){return `<button class="hot h-${id} ${done?'done':''}" data-hot="${id}" aria-label="${id}"></button>`}
function renderRoom(){const f=state.flags;q('#roomObjects').innerHTML=`<div class="villa ${f.power?'power-on':''} ${f.bookcase?'passage-open':''}"><div class="rain"></div><div class="flash"></div><div class="window"></div><div class="curtain"></div><div class="portrait"></div><div class="clock"></div><div class="desk"><div class="lamp"></div></div><div class="bookcase"><div class="books"></div></div><div class="door"></div><div class="dust"></div>${hot('portrait',f.portrait)}${hot('clock',f.clock)}${hot('desk',f.desk)}${hot('bookcase',f.bookcase)}${hot('door',f.door)}<div class="status">${statusText()}</div></div>`;q('#roomObjects').querySelectorAll('[data-hot]').forEach(x=>x.onclick=()=>inspect(x.dataset.hot))}
function statusText(){return ['Osserva ogni dettaglio: nulla è decorativo.','La cornice ha rivelato una lettera incompleta.','L’orologio ha liberato la chiave della scrivania.','Il diario contiene tre riferimenti per la libreria.','Il passaggio è aperto: manca solo l’ultima azione.'][Math.min(state.step,4)]}
function reset(){clearInterval(timer);remaining=15*60;Object.assign(state,{step:0,hints:3,notes:[],items:[],flags:{},sequence:[],sub:0});selected=null;q('#hintCount').textContent='3';q('#timer').textContent='15:00';renderRoom();renderInventory();show('game');intro()}
function intro(){modal('<h2>La Villa Abbandonata</h2><p>Ricci non ha lasciato un codice pronto: ha nascosto ogni informazione in più punti della stanza.</p><p>Esamina, confronta, ricostruisci e usa gli oggetti dell’inventario. Il timer inizierà quando entrerai.</p><button id="beginStory" class="primary">ENTRA NELLA VILLA</button>');q('#beginStory').onclick=()=>{close();startAt=Date.now();timer=setInterval(tick,1000)}}
function tick(){remaining=Math.max(0,15*60-Math.floor((Date.now()-startAt)/1000));q('#timer').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;if(!remaining){clearInterval(timer);modal('<h2>Tempo scaduto</h2><p>La polizia sigilla la villa prima che tu riesca ad aprire il passaggio.</p><button id="retry" class="primary">RIPROVA</button>');q('#retry').onclick=()=>{close();reset()}}}
function inspect(id){({portrait,clock,desk,bookcase,door}[id]||(()=>{}))()}
function portrait(){
 if(state.flags.portrait)return modal('<h2>Ritratto</h2><p>Le date corrette erano 1891, 1907, 1924. I simboli sul retro formavano luna, chiave, corvo.</p>');
 if(!state.flags.dates){state.sequence=[];modal('<h2>Enigma 1A — La genealogia</h2><p>Tre targhette appartengono alla stessa famiglia. Ordinale dalla nascita più antica alla più recente.</p><div class="puzzle-grid"><button data-date="1924">E. Ricci · 1924</button><button data-date="1891">A. Ricci · 1891</button><button data-date="1907">L. Ricci · 1907</button></div><p id="msg"></p>');q('#modalContent').querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{state.sequence.push(b.dataset.date);b.disabled=true;if(state.sequence.length===3){if(state.sequence.join('-')==='1891-1907-1924'){state.flags.dates=true;remember('Genealogia: 1891 → 1907 → 1924.');q('#msg').innerHTML='<span class="success">Il vetro si allenta. Dietro compaiono tre simboli.</span><button id="continuePortrait" class="primary">OSSERVA I SIMBOLI</button>';q('#continuePortrait').onclick=portrait}else{state.sequence=[];q('#modalContent').querySelectorAll('[data-date]').forEach(x=>x.disabled=false);q('#msg').innerHTML='<span class="error">L’ordine genealogico non torna.</span>'}}});return}
 state.sequence=[];modal('<h2>Enigma 1B — I simboli della cornice</h2><p>Le iniziali incise dicono: <strong>notte, accesso, presagio</strong>. Premi i simboli corrispondenti nello stesso ordine.</p><div class="puzzle-grid"><button data-symbol="K">🗝️</button><button data-symbol="R">🐦‍⬛</button><button data-symbol="M">🌙</button><button data-symbol="F">🔥</button></div><p id="msg"></p>');q('#modalContent').querySelectorAll('[data-symbol]').forEach(b=>b.onclick=()=>{state.sequence.push(b.dataset.symbol);if(state.sequence.length===3){if(state.sequence.join('')==='MKR'){state.flags.portrait=true;state.step=1;add('Lettera cifrata','✉️');remember('Simboli: luna → chiave → corvo. La lettera parla di una lancetta che mente.');renderRoom();q('#msg').innerHTML='<span class="success">La cornice libera una lettera piegata in quattro.</span>'}else{state.sequence=[];q('#msg').innerHTML='<span class="error">La cornice si richiude.</span>'}}})
}
function clock(){
 if(!state.flags.portrait)return modal('<h2>Orologio</h2><p>Il quadrante presenta segni strani, ma non hai ancora il testo per interpretarli.</p>');
 if(state.flags.clock)return modal('<h2>Orologio</h2><p>È fermo sulle 10:35. Il pendolo ha già liberato la chiave.</p>');
 if(!state.flags.clockTime){modal('<h2>Enigma 2A — La lettera cifrata</h2><p>“La campana suona <strong>cinque minuti dopo la mezza</strong>. La lancetta corta mostra sempre <strong>un’ora in meno</strong>. Sul quadrante leggi 09.”</p><p>Qual è l’ora reale?</p><div class="puzzle-grid"><button data-time="0935">09:35</button><button data-time="1035">10:35</button><button data-time="1135">11:35</button><button data-time="1005">10:05</button></div><p id="msg"></p>');q('#modalContent').querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{if(b.dataset.time==='1035'){state.flags.clockTime=true;remember('Ora reale: 10:35.');q('#msg').innerHTML='<span class="success">Le lancette si bloccano. Il pendolo emette tre rintocchi diversi.</span><button id="continueClock" class="primary">ASCOLTA I RINTOCCHI</button>';q('#continueClock').onclick=clock}else q('#msg').innerHTML='<span class="error">Il meccanismo respinge l’impostazione.</span>'});return}
 state.sequence=[];modal('<h2>Enigma 2B — Il pendolo</h2><p>I rintocchi sono: <strong>lungo, breve, breve, lungo</strong>. Riproducili.</p><div class="puzzle-grid"><button data-tone="L">— Lungo</button><button data-tone="B">• Breve</button></div><p id="msg"></p>');q('#modalContent').querySelectorAll('[data-tone]').forEach(b=>b.onclick=()=>{state.sequence.push(b.dataset.tone);q('#msg').textContent='Sequenza: '+state.sequence.map(x=>x==='L'?'—':'•').join(' ');if(state.sequence.length===4){if(state.sequence.join('')==='LBBL'){state.flags.clock=true;state.step=2;add('Chiave di ottone','🗝️');remember('Pendolo: lungo, breve, breve, lungo.');renderRoom();q('#msg').innerHTML='<span class="success">Il pendolo si apre e lascia cadere una chiave.</span>'}else{state.sequence=[];q('#msg').innerHTML='<span class="error">Ritmo errato. Il pendolo riparte.</span>'}}})
}
function desk(){
 if(!state.flags.clock)return modal('<h2>Scrivania</h2><p>I cassetti sono chiusi da una serratura in ottone.</p>');
 if(state.flags.desk)return modal('<h2>Scrivania</h2><p>Hai già ricostruito il diario e acceso la lampada.</p>');
 if(!chosen('Chiave di ottone'))return modal('<h2>Scrivania</h2><p>Seleziona la Chiave di ottone nell’inventario.</p>');
 if(!state.flags.drawer){remove('Chiave di ottone');state.flags.drawer=true;add('Quattro pagine','📄');remember('Nel cassetto: quattro pagine e una tabella con simboli meteo.');modal('<h2>Cassetto aperto</h2><p>Trovi quattro pagine senza numero e una tabella: ☀=1, ☁=2, ⛈=3, 🌙=4.</p><button id="continueDesk" class="primary">RICOSTRUISCI IL DIARIO</button>');q('#continueDesk').onclick=desk;return}
 if(!state.flags.pages){state.sequence=[];modal('<h2>Enigma 3A — Il diario frammentato</h2><p>Ordina gli eventi secondo la logica del racconto.</p><div class="puzzle-grid"><button data-page="D">Scopre una parete cava</button><button data-page="A">Entra nella villa</button><button data-page="S">Sente qualcuno dietro la libreria</button><button data-page="T">Il temporale spegne la luce</button></div><p id="msg"></p>');q('#modalContent').querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.sequence.push(b.dataset.page);b.disabled=true;if(state.sequence.length===4){if(state.sequence.join('')==='ATDS'){state.flags.pages=true;remember('Diario: arrivo → temporale → scoperta → suono dietro la libreria.');q('#msg').innerHTML='<span class="success">Le frasi combaciano. Ogni pagina mostra ora un simbolo meteo.</span><button id="continueDesk2" class="primary">DECODIFICA I SIMBOLI</button>';q('#continueDesk2').onclick=desk}else{state.sequence=[];q('#modalContent').querySelectorAll('[data-page]').forEach(x=>x.disabled=false);q('#msg').innerHTML='<span class="error">La storia non è coerente.</span>'}}});return}
 modal('<h2>Enigma 3B — La tabella meteo</h2><p>Sulle quattro pagine ordinate compaiono: <strong>🌙 ⛈ ☀</strong>. Usa la tabella del cassetto.</p><div class="code-input"><input id="diaryCode" inputmode="numeric" maxlength="3" placeholder="000"><button id="tryDiary">DECODIFICA</button></div><p id="msg"></p>');q('#tryDiary').onclick=()=>{if(q('#diaryCode').value==='431'){state.flags.desk=true;state.flags.power=true;state.step=3;remove('Quattro pagine');add('Diario completo','📕');add('Piastrina 431','🔖');remember('Simboli meteo decodificati: 4–3–1.');renderRoom();q('#msg').innerHTML='<span class="success">La lampada si accende e illumina tre libri segnati.</span>'}else q('#msg').innerHTML='<span class="error">La conversione non corrisponde alla tabella.</span>'}
}
function bookcase(){
 if(!state.flags.desk)return modal('<h2>Libreria</h2><p>Molti libri si muovono, ma non sai quali usare né in che modo.</p>');
 if(state.flags.bookcase)return modal('<h2>Libreria</h2><p>Il passaggio è già aperto.</p>');
 if(!state.flags.shelves){state.sequence=[];modal('<h2>Enigma 4A — I libri illuminati</h2><p>La lampada evidenzia i ripiani <strong>4, 3 e 1</strong>. Premili nell’ordine della piastrina.</p><div class="puzzle-grid"><button data-shelf="1">Ripiano 1</button><button data-shelf="2">Ripiano 2</button><button data-shelf="3">Ripiano 3</button><button data-shelf="4">Ripiano 4</button><button data-shelf="5">Ripiano 5</button></div><p id="msg"></p>');q('#modalContent').querySelectorAll('[data-shelf]').forEach(b=>b.onclick=()=>{state.sequence.push(b.dataset.shelf);if(state.sequence.length===3){if(state.sequence.join('')==='431'){state.flags.shelves=true;remember('Ripiani premuti: 4–3–1.');q('#msg').innerHTML='<span class="success">La libreria avanza di pochi centimetri. Compare una ruota con quattro direzioni.</span><button id="continueBooks" class="primary">AZIONA LA RUOTA</button>';q('#continueBooks').onclick=bookcase}else{state.sequence=[];q('#msg').innerHTML='<span class="error">I ripiani tornano in posizione.</span>'}}});return}
 state.sequence=[];modal('<h2>Enigma 4B — La ruota nascosta</h2><p>Nel diario Ricci ha scritto: “Segui il percorso della tempesta: <strong>nord, est, sud, est</strong>”.</p><div class="puzzle-grid"><button data-dir="N">↑</button><button data-dir="E">→</button><button data-dir="S">↓</button><button data-dir="W">←</button></div><p id="msg"></p>');q('#modalContent').querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>{state.sequence.push(b.dataset.dir);if(state.sequence.length===4){if(state.sequence.join('')==='NESE'){state.flags.bookcase=true;state.step=4;add('Maniglia del passaggio','🔩');remember('Ruota: nord → est → sud → est.');renderRoom();q('#msg').innerHTML='<span class="success">La libreria scorre lateralmente e rivela il passaggio.</span>'}else{state.sequence=[];q('#msg').innerHTML='<span class="error">La ruota si blocca e torna al centro.</span>'}}})
}
function door(){if(!state.flags.bookcase)return modal('<h2>Uscita</h2><p>La porta principale è saldata. Devi trovare il passaggio di Ricci.</p>');if(!chosen('Maniglia del passaggio'))return modal('<h2>Passaggio segreto</h2><p>Seleziona la Maniglia del passaggio nell’inventario.</p>');clearInterval(timer);const elapsed=15*60-remaining;localStorage.setItem('escapeV2Best',String(Math.min(Number(localStorage.getItem('escapeV2Best')||9999),elapsed)));q('#finalTime').textContent=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(elapsed%60).padStart(2,'0')}`;show('ending')}
function hint(){if(!state.hints)return modal('<h2>Indizi esauriti</h2><p>Rileggi gli appunti: contengono tutti i dati già scoperti.</p>');const hints=['Nel ritratto risolvi prima le date, poi traduci notte-accesso-presagio.','La lancetta corta segna un’ora in meno; dopo l’ora riproduci i rintocchi.','Seleziona la chiave, ricostruisci la storia e usa la tabella meteo.','La piastrina apre i ripiani; il diario indica le direzioni della ruota.','Seleziona la maniglia prima di toccare il passaggio.'];state.hints--;q('#hintCount').textContent=state.hints;modal(`<h2>Indizio</h2><p>${hints[Math.min(state.step,hints.length-1)]}</p>`)}
q('#openRoom').onclick=()=>show('briefing');q('#backHome').onclick=()=>show('home');q('#play').onclick=reset;q('#closeModal').onclick=close;q('#modal').onclick=e=>{if(e.target.id==='modal')close()};q('#hint').onclick=hint;q('#notes').onclick=()=>modal(`<h2>Appunti</h2>${state.notes.length?'<ul>'+state.notes.map(n=>`<li>${n}</li>`).join('')+'</ul>':'<p>Non hai ancora annotato nulla.</p>'}`);q('#audio').onclick=()=>{audioOn=!audioOn;q('#audio').textContent=audioOn?'🔊 Audio':'🔇 Audio'};q('#exit').onclick=()=>modal('<h2>Uscire dalla stanza?</h2><p>La partita corrente verrà persa.</p><button id="confirmExit" class="primary">ESCI</button>');document.addEventListener('click',e=>{if(e.target.id==='confirmExit'){clearInterval(timer);close();show('home')}});q('#endingHome').onclick=()=>show('home');
})();