(()=>{
const q=s=>document.querySelector(s);let timer=null,startAt=0,remaining=15*60,selected=null,audioOn=true;
const state={step:0,hints:3,notes:[],items:[],flags:{},sequence:[]};
const show=id=>{document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));window.scrollTo(0,0)};
const modal=html=>{q('#modalContent').innerHTML=html;q('#modal').classList.remove('hidden')};
const close=()=>q('#modal').classList.add('hidden');
const remember=t=>{if(!state.notes.includes(t))state.notes.push(t)};
const has=n=>state.items.some(i=>i.name===n),chosen=n=>selected===n&&has(n);
function add(name,icon){if(!has(name))state.items.push({name,icon});renderInventory()}
function remove(name){state.items=state.items.filter(i=>i.name!==name);if(selected===name)selected=null;renderInventory()}
function renderInventory(){const b=q('#items');b.innerHTML=state.items.length?state.items.map(i=>`<button class="item ${selected===i.name?'selected':''}" data-item="${i.name}"><span>${i.icon}</span>${i.name}</button>`).join(''):'<span style="color:#69737f">Vuoto</span>';b.querySelectorAll('[data-item]').forEach(x=>x.onclick=()=>{selected=selected===x.dataset.item?null:x.dataset.item;renderInventory()})}
function hot(id,done){return `<button class="hot h-${id} ${done?'done':''}" data-hot="${id}" aria-label="${id}"></button>`}
function renderRoom(){const f=state.flags;q('#roomObjects').innerHTML=`<div class="villa"><div class="rain"></div><div class="flash"></div><div class="window"></div><div class="curtain"></div><div class="portrait"></div><div class="clock"></div><div class="desk"><div class="lamp"></div></div><div class="bookcase"><div class="books"></div></div><div class="door"></div><div class="dust"></div>${hot('portrait',f.portrait)}${hot('clock',f.clock)}${hot('desk',f.desk)}${hot('bookcase',f.bookcase)}${hot('door',f.door)}<div class="status">${statusText()}</div></div>`;q('#roomObjects').querySelectorAll('[data-hot]').forEach(x=>x.onclick=()=>inspect(x.dataset.hot))}
function statusText(){return ['Esplora la villa e ricostruisci ciò che è accaduto.','Confronta ritratto, lettera e orologio.','Usa la chiave sulla scrivania.','Ricostruisci il diario dell’investigatore.','Sblocca il passaggio dietro la libreria.'][Math.min(state.step,4)]}
function reset(){clearInterval(timer);remaining=15*60;startAt=Date.now();Object.assign(state,{step:0,hints:3,notes:[],items:[],flags:{},sequence:[]});selected=null;q('#hintCount').textContent='3';q('#timer').textContent='15:00';renderRoom();renderInventory();show('game');intro();}
function intro(){modal('<h2>La Villa Abbandonata</h2><p>La pioggia copre ogni rumore. L’investigatore Ricci è entrato qui tre giorni fa e non è più uscito.</p><p>Trova il suo diario e apri il passaggio segreto prima che la villa venga sigillata.</p><button id="beginStory" class="primary">ENTRA NELLA VILLA</button>');q('#beginStory').onclick=()=>{close();startAt=Date.now();timer=setInterval(tick,1000)}}
function tick(){remaining=Math.max(0,15*60-Math.floor((Date.now()-startAt)/1000));q('#timer').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;if(!remaining){clearInterval(timer);modal('<h2>Tempo scaduto</h2><p>La villa viene sigillata prima che tu riesca a uscire.</p><button id="retry" class="primary">RIPROVA</button>');q('#retry').onclick=()=>{close();reset()}}}
function inspect(id){({portrait,clock,desk,bookcase,door}[id]||(()=>{}))()}
function portrait(){if(state.flags.portrait)return modal('<h2>Ritratto</h2><p>Dietro la cornice: “La lancetta corta mente. Guarda le tre date.”</p>');state.sequence=[];modal('<h2>Enigma 1 — Il ritratto</h2><p>Dietro la cornice trovi tre targhette. Ordinale dalla più vecchia alla più recente.</p><div class="puzzle-grid"><button data-date="1891">1891</button><button data-date="1924">1924</button><button data-date="1907">1907</button></div><p id="msg"></p>');q('#modalContent').querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{state.sequence.push(b.dataset.date);b.disabled=true;if(state.sequence.length===3){if(state.sequence.join('-')==='1891-1907-1924'){state.flags.portrait=true;state.step=1;add('Lettera strappata','✉️');remember('Date corrette: 1891 → 1907 → 1924. Dietro il ritratto: la lancetta corta mente.');renderRoom();q('#msg').innerHTML='<span class="success">La cornice scatta e libera una lettera.</span>'}else{state.sequence=[];q('#modalContent').querySelectorAll('[data-date]').forEach(x=>x.disabled=false);q('#msg').innerHTML='<span class="error">Ordine errato.</span>'}}})}
function clock(){if(!state.flags.portrait)return modal('<h2>Orologio</h2><p>Il quadrante non offre ancora abbastanza informazioni.</p>');if(state.flags.clock)return modal('<h2>Orologio</h2><p>Le lancette segnano 10:35. Nel vano interno non è rimasto altro.</p>');modal('<h2>Enigma 2 — L’orologio bugiardo</h2><p>La lettera dice: “Dieci passi dopo la mezz’ora. La lancetta corta mente di un’ora.”</p><p>Quale ora devi impostare?</p><div class="puzzle-grid"><button data-time="0935">09:35</button><button data-time="1035">10:35</button><button data-time="1135">11:35</button></div><p id="msg"></p>');q('#modalContent').querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{if(b.dataset.time==='1035'){state.flags.clock=true;state.step=2;add('Chiave di ottone','🗝️');remember('Orologio impostato alle 10:35.');renderRoom();q('#msg').innerHTML='<span class="success">Un piccolo vano si apre dietro il quadrante.</span>'}else q('#msg').innerHTML='<span class="error">Le lancette tornano indietro.</span>'})}
function desk(){if(!state.flags.clock)return modal('<h2>Scrivania</h2><p>I cassetti sono chiusi.</p>');if(state.flags.desk)return modal('<h2>Scrivania</h2><p>Hai già ricostruito il diario.</p>');if(!chosen('Chiave di ottone'))return modal('<h2>Scrivania</h2><p>Seleziona la Chiave di ottone nell’inventario.</p>');remove('Chiave di ottone');state.sequence=[];modal('<h2>Enigma 3 — Il diario frammentato</h2><p>Nel cassetto trovi quattro pagine. Ordinale seguendo gli eventi: arrivo, temporale, scoperta, sparizione.</p><div class="puzzle-grid"><button data-page="A">Arrivo</button><button data-page="S">Sparizione</button><button data-page="D">Scoperta</button><button data-page="T">Temporale</button></div><p id="msg"></p>');q('#modalContent').querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.sequence.push(b.dataset.page);b.disabled=true;if(state.sequence.length===4){if(state.sequence.join('')==='ATDS'){state.flags.desk=true;state.step=3;add('Diario completo','📕');add('Piastrina 731','🔖');remember('Diario: arrivo → temporale → scoperta → sparizione. Piastrina trovata: 731.');renderRoom();q('#msg').innerHTML='<span class="success">Sul dorso delle pagine compare la sequenza 7–3–1.</span>'}else{state.sequence=[];q('#modalContent').querySelectorAll('[data-page]').forEach(x=>x.disabled=false);q('#msg').innerHTML='<span class="error">Le pagine non combaciano.</span>'}}})}
function bookcase(){if(!state.flags.desk)return modal('<h2>Libreria</h2><p>Alcuni libri sembrano mobili, ma manca un criterio.</p>');if(state.flags.bookcase)return modal('<h2>Libreria</h2><p>Il meccanismo è già attivo.</p>');state.sequence=[];modal('<h2>Enigma 4 — Il passaggio segreto</h2><p>La piastrina indica 7–3–1. Premi i ripiani corrispondenti nell’ordine corretto.</p><div class="puzzle-grid"><button data-shelf="1">1</button><button data-shelf="3">3</button><button data-shelf="5">5</button><button data-shelf="7">7</button><button data-shelf="9">9</button></div><p id="msg"></p>');q('#modalContent').querySelectorAll('[data-shelf]').forEach(b=>b.onclick=()=>{state.sequence.push(b.dataset.shelf);if(state.sequence.length===3){if(state.sequence.join('')==='731'){state.flags.bookcase=true;state.step=4;add('Maniglia nascosta','🔩');remember('Libreria sbloccata con 7–3–1.');renderRoom();q('#msg').innerHTML='<span class="success">La libreria si sposta e rivela una porta interna.</span>'}else{state.sequence=[];q('#msg').innerHTML='<span class="error">Il meccanismo si azzera.</span>'}}})}
function door(){if(!state.flags.bookcase)return modal('<h2>Uscita</h2><p>La porta principale è bloccata. Deve esistere un altro passaggio.</p>');if(!chosen('Maniglia nascosta'))return modal('<h2>Passaggio segreto</h2><p>Seleziona la Maniglia nascosta nell’inventario.</p>');clearInterval(timer);const elapsed=15*60-remaining;localStorage.setItem('escapeV2Best',String(Math.min(Number(localStorage.getItem('escapeV2Best')||9999),elapsed)));q('#finalTime').textContent=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(elapsed%60).padStart(2,'0')}`;show('ending')}
function hint(){if(!state.hints)return modal('<h2>Indizi esauriti</h2><p>Controlla gli appunti e gli oggetti già trovati.</p>');const hints=['Nel ritratto devi ordinare le date.','La lettera descrive le 10:35.','Seleziona la chiave prima di toccare la scrivania.','Ordina le pagine: arrivo, temporale, scoperta, sparizione.','La piastrina indica 7–3–1.'];state.hints--;q('#hintCount').textContent=state.hints;modal(`<h2>Indizio</h2><p>${hints[Math.min(state.step,hints.length-1)]}</p>`)}
q('#openRoom').onclick=()=>show('briefing');q('#backHome').onclick=()=>show('home');q('#play').onclick=reset;q('#closeModal').onclick=close;q('#modal').onclick=e=>{if(e.target.id==='modal')close()};q('#hint').onclick=hint;q('#notes').onclick=()=>modal(`<h2>Appunti</h2>${state.notes.length?'<ul>'+state.notes.map(n=>`<li>${n}</li>`).join('')+'</ul>':'<p>Non hai ancora annotato nulla.</p>'}`);q('#audio').onclick=()=>{audioOn=!audioOn;q('#audio').textContent=audioOn?'🔊 Audio':'🔇 Audio'};q('#exit').onclick=()=>modal('<h2>Uscire dalla stanza?</h2><p>La partita corrente verrà persa.</p><button id="confirmExit" class="primary">ESCI</button>');document.addEventListener('click',e=>{if(e.target.id==='confirmExit'){clearInterval(timer);close();show('home')}});q('#endingHome').onclick=()=>show('home');
})();